
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-standalone
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-standalone
  template:
    metadata:
      labels:
        app: mongodb-standalone
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo:4.0.8
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-standalone
  namespace: mongo
  labels:
    app: mongodb-standalone
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb-standalone
  type: ClusterIP